name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          - aarch64-unknown-linux-musl
        include:
          - target: aarch64-unknown-linux-musl
            container_platform: linux/arm64/v8
    env:
      registry: ghcr.io/${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: build image
        run: >
          docker build .
          --tag "${{ env.registry }}/fernbedienung:$(date +%s)"
          --platform "${{ matrix.container_platform }}"
          --build-args "TARGET=${{ matrix.target }}"
      - name: push image
        run: docker push "${{ env.name }}/fernbedienung"
